name: espana_en_cifras
channels:
  - conda-forge
dependencies:
  - python=3.8 
  - bokeh
  - numpy
  - jupyterlab
  - numba
  - pandas
  - holoviews
  - tqdm
  - geopandas
  - ipywidgets
  - pip:
    - xlrd
    - ray
    - scanpy
    - leidenalg
